# Site wide configuration
description: "This is a description of my awesome site."
locale: en
logo: ~
path: atom.xml
teaser: mirv1.jpg
title: "Jon Askonas"
url:

# Jekyll configuration

gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
highlighter: rouge
kramdown:
  toc_levels: "1..2"
permalink: "/:categories/:title/"
sass:
  sass_dir: _sass
  style: compressed


#Site owner
avatar: jaskonas_portrait.png
name: "Jon Askonas"
owner: "Jon Askonas"
twitter: "@jonaskonas"

include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
